### ISSUE TITLE
Tome of Town Portal Bug

### ISSUE THREAD

**Issue by toddtmw** [dschu012/d2s-editor#36] opened 2021-10-11 23:21 UTC
Hi. I think there might be a bug that causes the tome of town portal to become a tome of identify when you save. (I mean, I guess it could be during load, I only notice it when I get back in the game and go to use town portal and it is identify.)

The tome is blue like the town portal tome, but it casts identify when you try to use it.

Thanks.

**Comment by dschu012** [comment] 2021-10-13 17:33
Duplicate of #3

**Closed as completed by dschu012** 2021-10-13 17:33 UTC
