### ISSUE TITLE
Book of Teleportation

### ISSUE THREAD

**Issue by ArmetisaGitHub** [dschu012/d2s-editor#9] opened 2021-09-25 00:41 UTC
The book doesn't work when in game.   Would it be possible to add more runewords items (ex:  the shield Sanctuary (ko ko mal), gems would be nice too.  other than that it's very nice editor.  nice job

**Comment by dschu012** [comment] 2021-09-25 03:33
duplicate of #3

**Closed by dschu012** 2021-09-25 03:33 UTC
