### ISSUE TITLE
Can someone please explain how to edit existing chars?

### ISSUE THREAD

**Issue by Bogdanov89** [dschu012/d2s-editor#88] opened 2022-04-15 15:07 UTC
So far the only functional way of doing something with the editor was to create a brand new char through it.
However if i try to edit any char i get this file that i am not sure what to do with, and if i place it in the save game folder (as renamed) and try to load it my game goes something like "failed to join" (offline).

Can someone please explain what to do after editing an existing character?
What to do with the file that it creates as a save?

**Comment by dschu012** [comment] 2022-04-17 15:52
Duplicate of #89

**Closed by dschu012** 2022-04-17 15:52 UTC

**Comment by Bogdanov89** [comment] 2022-04-17 16:26
I found a solution to my problem, the editor will not fill the Name of a character that you load (it will be blank).
If i type the name as my character is named and copy/overwrite the file it will work normally.
So in my case the only issue is that the editor when opening existing characters does not fill the char name (leaves it blank) and that breaks the loading.
