### ISSUE TITLE
Tome of Town Portal converted to Tome of Identify after editing/saving Character

### ISSUE THREAD

**Issue by MisterBLC** [dschu012/d2s-editor#10] opened 2021-09-25 02:53 UTC
Tome of Town Portal converted to Tome of Identify after editing/saving Character.  Tome is broken in game after that, must be sold and a new tome bought.

**Comment by dschu012** [comment] 2021-09-25 03:33
duplicate of #3

**Closed by dschu012** 2021-09-25 03:33 UTC
