### ISSUE TITLE
Adding items to inventory causes problem with Tomes

### ISSUE THREAD

**Issue by vennyp0o** [dschu012/d2s-editor#74] opened 2022-01-14 18:55 UTC
Hello!  

*I see this looks to be a similar or equal issue to #73 'Tome of Town Portal bug' reported by lehandroz two days ago.  

In uploading a D2:R 'toon.d2s' file:

Loading any item (testing only from the site's built-in drop-down list so far) to the inventory of a raw, offline, L16 toon that has never been played with any mod, will conjure what appears to be the correct item(s) but in doing so, regardless of item type, the tomes of Identify and Town Portal get mixed or combined somehow.  I still need to test other options, and I haven't yet noticed any other effects besides this.  

Pictures attached.  Thanks much for the tool!  This is almost as much fun as playing the game itself.  
V

![1 - dschu012_d2s-editor_Preload](https://user-images.githubusercontent.com/97754232/149569689-12b4ad0d-c94d-40c1-9659-b6e2b1986379.JPG)
![2 - dschu012_d2s-editor_Postload](https://user-images.githubusercontent.com/97754232/149569691-6a64cd17-e926-4838-94a0-5976ca7a6c97.JPG)

**Comment by vennyp0o** [comment] 2022-01-14 19:06
OK, reading back further it looks like this issue has been around a while; probably beyond a nonuplicate at this point.  ;o)

**Comment by vennyp0o** [comment] 2022-01-14 19:22
Loading an item to Stash conjures same behavior.  Also, as I believe was said previously, the name of Tome of Town Portal is changed to Tom of Identify.  

Additionally confirmed is that dropping and re-buying the tomes and filling them appears to correct the problem, including the hotkey issue as in the pics.  Just can't know for sure what other items are affected as of yet and thus not safely playable.

**Comment by dschu012** [comment] 2022-01-25 14:15
Duplicate of #3

**Closed by dschu012** 2022-01-25 14:15 UTC
